### ISSUE TITLE
Warlock Tainted Scholar Inaccurate Pre-Requisites

### ISSUE THREAD

**Issue by Habreno** [Maetrim/DDOBuilderV2#165]
Warlock's Tainted Scholar tree has a T3 enhancement "Efficient Heighten" with an erroneous requirement for the feat "Heighten Spell" that it does not actually have in-game.

https://cdn.discordapp.com/attachments/903669616046374933/1286763350734274620/image.png?ex=66f30bc1&is=66f1ba41&hm=43c325bf0a560c88962e9b9ad26b7fc1c7dd44b3b391ab29ed81d764853aebaf&
https://cdn.discordapp.com/attachments/903669616046374933/1286763351115960391/image.png?ex=66f30bc1&is=66f1ba41&hm=f87a5fef50f119d587190733c76c1792bc04b8558bc05b41c6be7a4d29238584&

I cannot confirm nor deny the exclusivity requirement, so I would recommend that be checked as well.

**Comment by Maetrim** [comment]
Although the wiki says there are no requirements. I deliberately made the software exclude taking this enhancement if you did not have the "Heighten Spell" feat (its just a waste of points otherwise). I have updated the requirements to work for "Heighten Spell" from any source though in case you can get it from a non-feat source. (Done for all enhancement tree with an Efficient Heighten option)
