### ISSUE TITLE
Defensive Stances - Not allowing Combat Expertise and Stalwart Defense at the same time

### ISSUE THREAD

**Issue by Ibtaken** [Maetrim/DDOBuilderV2#46]
Defensive stances from enhancement trees (e.g. Stalwart Defender) are currently mutually exclusive with Combat Expertise/Defensive Fighting, but they can both be activated at the same time in-game.

**Comment by tevwoods** [comment]
Just wanted to second this.

If I might make a suggestion, since DDO doesn't seem to be very consistent about which stances can be simultaneously active, it might be a good idea to define for each stance an exclusion list of other stances that aren't valid with that stance, rather than relying on a simple categorization approach.

If the categorization approach is desired, then I think that stances like Stalwart Defense, Sacred Defense, and Nature's Defense should be in a different category from the feat-based defensive stances.

**Comment by Maetrim** [comment]
Tev, Thats how it exactly used to work in V1 of the builder. Its a machanism I will restore for V2 and move all the combat stances into the User group. But not tonight, I am knackared :D

**Comment by tevwoods** [comment]
All good! Awesome work by the way, love the tool!

**Comment by Maetrim** [comment]
Should be fixed in the next version. Its worth checking I put the right Incompatibles with the right stances though :D
